/* OSU Robotics Club Rover 2016
 * Miniboard Firmware
 *
 * comm.h - Non-autogenerated portion of the communication module.
 *          This works with the commgen.c/.h files to implement the 
 *          computer control interface.
 */
#define COMM_UART 0

/* Configure the computer communications uart. */
void comm_init(void);