/* Warning: This file is automatically generated. Do not modify. */
#include <stdint.h>
#include <string.h>
#include "commgen.h"

struct comm_data_t DataReal = {
	.pause_state = 1,
	.left_drive = 0,
	.right_drive = 0,
	.swerve_state = 0,
	.selected_camera = 0,
};
volatile struct comm_data_t *Data = &DataReal;
/* Note: Sent as a reply to unknown commands. */
void parse_command_not_recognized(uint8_t *packet, uint8_t *wrong_command){
	uint16_t b = 1;
	unpack8(packet, b, (uint8_t *) wrong_command);
	b += 1;
}

/* Note: Sent as a reply to unknown commands. */
void send_command_not_recognized(uint8_t wrong_command){
	uint16_t b = 1;
	uint8_t buf[2];
	buf[0] = 0x0;
	pack8(buf, b, wrong_command);
	b += 1;
	send_packet(buf, b);
}

/* Note: 0 = pause (no rover motion) 1 = unpause */
void parse_pause(uint8_t *packet, uint8_t *pause_state){
	uint16_t b = 1;
	unpack8(packet, b, (uint8_t *) pause_state);
	b += 1;
}

/* Note: 0 = pause (no rover motion) 1 = unpause */
void send_pause(uint8_t pause_state){
	uint16_t b = 1;
	uint8_t buf[2];
	buf[0] = 0x5;
	pack8(buf, b, pause_state);
	b += 1;
	send_packet(buf, b);
}

/* Note: Battery voltage in mV */
void parse_battery_voltage(uint8_t *packet, uint16_t *battery_voltage){
	uint16_t b = 1;
	unpack16(packet, b, (uint16_t *) battery_voltage);
	b += 2;
}

/* Note: Battery voltage in mV */
void send_battery_voltage(uint16_t battery_voltage){
	uint16_t b = 1;
	uint8_t buf[3];
	buf[0] = 0x6;
	pack16(buf, b, battery_voltage);
	b += 2;
	send_packet(buf, b);
}

/* Note: -127 = full reverse 128 = full forward */
void parse_drive_motor_power(uint8_t *packet, int8_t *left_drive, int8_t *right_drive){
	uint16_t b = 1;
	unpack8(packet, b, (uint8_t *) left_drive);
	b += 1;
	unpack8(packet, b, (uint8_t *) right_drive);
	b += 1;
}

/* Note: -127 = full reverse 128 = full forward */
void send_drive_motor_power(int8_t left_drive, int8_t right_drive){
	uint16_t b = 1;
	uint8_t buf[3];
	buf[0] = 0x10;
	pack8(buf, b, left_drive);
	b += 1;
	pack8(buf, b, right_drive);
	b += 1;
	send_packet(buf, b);
}

/* Note: 0x00 = Off (no motion), 0x01 = Straight, 0x02 = Turn */
void parse_swerve_drive_state(uint8_t *packet, uint8_t *swerve_state){
	uint16_t b = 1;
	unpack8(packet, b, (uint8_t *) swerve_state);
	b += 1;
}

/* Note: 0x00 = Off (no motion), 0x01 = Straight, 0x02 = Turn */
void send_swerve_drive_state(uint8_t swerve_state){
	uint16_t b = 1;
	uint8_t buf[2];
	buf[0] = 0x11;
	pack8(buf, b, swerve_state);
	b += 1;
	send_packet(buf, b);
}

/* Note: 0-3; select camera feed to send to the base station and to send commands to.
 * TODO: define which camera corresponds to which number */
void parse_select_camera(uint8_t *packet, uint8_t *selected_camera){
	uint16_t b = 1;
	unpack8(packet, b, (uint8_t *) selected_camera);
	b += 1;
}

/* Note: 0-3; select camera feed to send to the base station and to send commands to.
 * TODO: define which camera corresponds to which number */
void send_select_camera(uint8_t selected_camera){
	uint16_t b = 1;
	uint8_t buf[2];
	buf[0] = 0x20;
	pack8(buf, b, selected_camera);
	b += 1;
	send_packet(buf, b);
}

/* Note: Custom camera commands defined in camera manual. camera_data_length defines the
 * number of data bytes in the command (0-255). camera_data is the command to be
 * sent to the camera. */
void parse_camera_command(uint8_t *packet, uint8_t *camera_data_length, uint8_t  *camera_data){
	uint16_t b = 1;
	unpack8(packet, b, (uint8_t *) camera_data_length);
	b += 1;
	memcpy(camera_data, packet + b, *camera_data_length);
	b += *camera_data_length;
}

/* Note: Custom camera commands defined in camera manual. camera_data_length defines the
 * number of data bytes in the command (0-255). camera_data is the command to be
 * sent to the camera. */
void send_camera_command(uint8_t camera_data_length, uint8_t * camera_data){
	uint16_t b = 1;
	uint8_t buf[257];
	buf[0] = 0x30;
	pack8(buf, b, camera_data_length);
	b += 1;
	memcpy(buf + b, camera_data, camera_data_length);
	b += camera_data_length;
	send_packet(buf, b);
}

/* Note: Read out the latest debug message. */
void parse_debugging_info(uint8_t *packet, uint8_t *debug_str_length, uint8_t  *debug_str_data){
	uint16_t b = 1;
	unpack8(packet, b, (uint8_t *) debug_str_length);
	b += 1;
	memcpy(debug_str_data, packet + b, *debug_str_length);
	b += *debug_str_length;
}

/* Note: Read out the latest debug message. */
void send_debugging_info(uint8_t debug_str_length, uint8_t * debug_str_data){
	uint16_t b = 1;
	uint8_t buf[257];
	buf[0] = 0x50;
	pack8(buf, b, debug_str_length);
	b += 1;
	memcpy(buf + b, debug_str_data, debug_str_length);
	b += debug_str_length;
	send_packet(buf, b);
}

void pack8(uint8_t *data, uint16_t pos, uint8_t value){
	*(data + pos + 0) = (value >> 0) & 0xFF;
}
void unpack8(uint8_t *data, uint16_t pos, uint8_t *result){
	*result = (((uint8_t) *(data + pos + 0) << 0));
}
void pack16(uint8_t *data, uint16_t pos, uint16_t value){
	*(data + pos + 0) = (value >> 0) & 0xFF;
	*(data + pos + 1) = (value >> 8) & 0xFF;
}
void unpack16(uint8_t *data, uint16_t pos, uint16_t *result){
	*result = (((uint16_t) *(data + pos + 0) << 0)) | (((uint16_t) *(data + pos + 1) << 8));
}
void pack32(uint8_t *data, uint16_t pos, uint32_t value){
	*(data + pos + 0) = (value >> 0) & 0xFF;
	*(data + pos + 1) = (value >> 8) & 0xFF;
	*(data + pos + 2) = (value >> 16) & 0xFF;
	*(data + pos + 3) = (value >> 24) & 0xFF;
}
void unpack32(uint8_t *data, uint16_t pos, uint32_t *result){
	*result = (((uint32_t) *(data + pos + 0) << 0)) | (((uint32_t) *(data + pos + 1) << 8)) | (((uint32_t) *(data + pos + 2) << 16)) | (((uint32_t) *(data + pos + 3) << 24));
}
void pack64(uint8_t *data, uint16_t pos, uint64_t value){
	*(data + pos + 0) = (value >> 0) & 0xFF;
	*(data + pos + 1) = (value >> 8) & 0xFF;
	*(data + pos + 2) = (value >> 16) & 0xFF;
	*(data + pos + 3) = (value >> 24) & 0xFF;
	*(data + pos + 4) = (value >> 32) & 0xFF;
	*(data + pos + 5) = (value >> 40) & 0xFF;
	*(data + pos + 6) = (value >> 48) & 0xFF;
	*(data + pos + 7) = (value >> 56) & 0xFF;
}
void unpack64(uint8_t *data, uint16_t pos, uint64_t *result){
	*result = (((uint64_t) *(data + pos + 0) << 0)) | (((uint64_t) *(data + pos + 1) << 8)) | (((uint64_t) *(data + pos + 2) << 16)) | (((uint64_t) *(data + pos + 3) << 24)) | (((uint64_t) *(data + pos + 4) << 32)) | (((uint64_t) *(data + pos + 5) << 40)) | (((uint64_t) *(data + pos + 6) << 48)) | (((uint64_t) *(data + pos + 7) << 56));
}
void parse_packet(uint8_t *buf, uint16_t count){	uint8_t cmd = buf[0];
	switch(cmd){
		/* Command not Recognized */
		case 0x00: /* (Write form) */
			parse_command_not_recognized(buf, &(DataReal.wrong_command));
			buf[0] = cmd;
			send_packet(buf, 1);
			break;
		case 0x80: /* (Read form) */
			send_command_not_recognized(DataReal.wrong_command);
			break;
		/* Pause */
		case 0x05: /* (Write form) */
			parse_pause(buf, &(DataReal.pause_state));
			buf[0] = cmd;
			send_packet(buf, 1);
			break;
		case 0x85: /* (Read form) */
			send_pause(DataReal.pause_state);
			break;
		/* Battery voltage */
		case 0x06: /* (Write form) */
			parse_battery_voltage(buf, &(DataReal.battery_voltage));
			buf[0] = cmd;
			send_packet(buf, 1);
			break;
		case 0x86: /* (Read form) */
			send_battery_voltage(DataReal.battery_voltage);
			break;
		/* Drive Motor Power */
		case 0x10: /* (Write form) */
			parse_drive_motor_power(buf, &(DataReal.left_drive), &(DataReal.right_drive));
			buf[0] = cmd;
			send_packet(buf, 1);
			break;
		case 0x90: /* (Read form) */
			send_drive_motor_power(DataReal.left_drive, DataReal.right_drive);
			break;
		/* Swerve Drive State */
		case 0x11: /* (Write form) */
			parse_swerve_drive_state(buf, &(DataReal.swerve_state));
			buf[0] = cmd;
			send_packet(buf, 1);
			break;
		case 0x91: /* (Read form) */
			send_swerve_drive_state(DataReal.swerve_state);
			break;
		/* Select Camera */
		case 0x20: /* (Write form) */
			parse_select_camera(buf, &(DataReal.selected_camera));
			buf[0] = cmd;
			send_packet(buf, 1);
			break;
		case 0xA0: /* (Read form) */
			send_select_camera(DataReal.selected_camera);
			break;
		/* Camera Command */
		case 0x30: /* (Write form) */
			parse_camera_command(buf, &(DataReal.camera_data_length), DataReal.camera_data);
			buf[0] = cmd;
			send_packet(buf, 1);
			camera_command_trigger();
			break;
		case 0xB0: /* (Read form) */
			send_camera_command(DataReal.camera_data_length, DataReal.camera_data);
			break;
		/* Debugging Info */
		case 0x50: /* (Write form) */
			parse_debugging_info(buf, &(DataReal.debug_str_length), DataReal.debug_str_data);
			buf[0] = cmd;
			send_packet(buf, 1);
			debugging_info_trigger();
			break;
		case 0xD0: /* (Read form) */
			send_debugging_info(DataReal.debug_str_length, DataReal.debug_str_data);
			break;
		default:
			buf[0] = 0;
			send_packet(buf, 1);
			break;
	}
}
